name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:

  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create object folder
      run: mkdir objs
    - name: create build folder
      run: mkdir build
    - name: make
      run: make cmd
    - name: cleanup
      run: rm -rf objs
    - name: upload code generator
      uses: actions/upload-artifact@v2
      with:
        name: codegenerator linux
        path: build/CodeGenerator
      
  windows_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: create object folder
      run: mkdir objs
    - name: create build folder
      run: mkdir build
    - name: make
      run: make cmdWin
    - name: cleanup
      run: rm -rf objs
    - name: upload code generator
      uses: actions/upload-artifact@v2
      with:
        name: CodeGenerator.exe
        path: build/CodeGenerator.exe

  osx_build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: create object folder
      run: mkdir objs
    - name: create build folder
      run: mkdir build
    - name: make
      run: make cmdOSX
    - name: cleanup
      run: rmdir objs
    - name: upload code generator
      uses: actions/upload-artifact@v2
      with:
        name: CodeGenerator_OSX
        path: build/CodeGenerator_OSX
